on:
  workflow_call:
    inputs:
      tag: { required: true, type: string }
      app_name: { required: true, type: string }
      registry: { required: true, type: string, description: "URL do registry no Artifact Registry" }
      gcp_workload_identity_provider: { required: true, type: string }
      gcp_service_account: { required: true, type: string }
      gke_cluster_name: { required: true, type: string }
      gke_cluster_location: { required: true, type: string }
      namespace: { required: true, type: string }
      values_file: { required: true, type: string }

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ inputs.namespace }}-${{ inputs.app_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ inputs.gke_cluster_name }}
          location: ${{ inputs.gke_cluster_location }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "v3.12.0"

      - name: Helm OCI Login (Artifact Registry)
        run: |
          gcloud auth print-access-token \
          | helm registry login \
              --username oauth2accesstoken \
              --password-stdin \
              ${{ inputs.registry }}

      - name: Verify Helm Release Status
        run: |
          RELEASE_EXISTS=$(helm ls -n ${{ inputs.namespace }} --all --output json | jq '.[] | select((.name=="'${{ inputs.app_name }}'")) | .name')
          if [ -n "$RELEASE_EXISTS" ]; then
              RELEASE_STATUS=$(helm status ${{ inputs.app_name }} -n ${{ inputs.namespace }} --output json | jq -r '.info.status')
              echo "Release in status $RELEASE_STATUS"

              if [ "$RELEASE_STATUS" == "pending-install" ] || [ "$RELEASE_STATUS" == "pending-upgrade" ] || [ "$RELEASE_STATUS" == "pending-rollback" ]; then
                  echo "Rollback started..."
                  helm rollback ${{ inputs.app_name }} -n ${{ inputs.namespace }}
                  if [ $? -ne 0 ]; then
                      echo "Error during rollback of release ${{ inputs.app_name }}. Exiting..."
                      exit 1
                  fi
              fi
          fi
          
      - name: Verify and Deploy
        run: |
          helm upgrade --install \
          -f ${{ inputs.values_file }} \
          ${{ inputs.app_name }} \
          oci://${{ inputs.registry }}/helm-chart \
          --namespace ${{ inputs.namespace }} \
          --set namespace=${{ inputs.namespace }} \
          --force \
          --wait \
          --timeout 10m0s \
          --set="appVersion=${{ inputs.tag }}" \
          --set="job.jobs[0].image.tag=${{ inputs.tag }}" \
          --version 2.0.0